### ISSUE TITLE
zrup rzeby łatfo morzna było prostokont narysować

### ISSUE THREAD

**Issue by djedr** [rzuf79/chao.js#2]

**Comment by djedr** [comment]
bo nie mogłem w tym paserze ogarnąć
dokumentacja do czego innego niż teges
przykłady w cały świat

**Comment by djedr** [comment]
`drawRect` chyba to robi co hciałem
wienc morzna zamknońć hyba

**Comment by djedr** [comment]
no to zamyka

**Comment by rzuf79** [comment]
@djedr 
bo dokumentacja do pejsera (pierwszego syjonistycznego wszechframeworku) jest w jakimś limbo pomiędzy wersjami 2 i 3, co to wywróciła wszystko do góry nogami.
a jak brakuje jakiegoś oczywistego ficzerka to pewnie jest zaksięgowany gdzieś [tutej](https://github.com/rzuf79/chao.js/projects)
